### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [pablo-dev/HomeCloudAndroidWS#1]
Greetings, I just made a logo for your project, hope you like it.
![homecloud](https://user-images.githubusercontent.com/35619342/39495573-d6bdfd46-4d68-11e8-81c8-147a68a1ad72.png)
If you liked it, let me know which variation and I'll upload the files on a pull request.
Please tell me if you want me to add/modify something. :))

**Comment by pablo-dev** [comment]
Hi
The logos are great but I already did a deep search to find the best option and will stick with the current one for now.
Thanks.
